### ISSUE TITLE
backtest sync data fail

### ISSUE THREAD

**Issue by tony1223** [c9s/bbgo#288]
Got error messages. QQ

`[0000] FATAL cannot execute command error=Error 1264: Out of range value for column 'taker_buy_base_volume' at row 1
`

Enviroment: 

`bbgo backtest --exchange binance -v --sync --sync-only --sync-from 2021-11-01 --config bbgo.yaml 
`
```
backtest: 
  startTime: "2021-11-25" 
  endTime: "2022-11-30" 
  symbols: 
  - XRPUSDT 
  account: 
    balances: 
      XRP: 0.0 
      BTC: 0.0 
      USDT: 10000.0
```

Tested it will work if i modify the column size manually. (from decimal(16,8) to decimal(32,8) )
`
ALTER TABLE binance_klines CHANGE  taker_buy_base_volume  taker_buy_base_volume   decimal(32,8) NOT NULL

`
