### ISSUE TITLE
Backfill failing.

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#290]
Backfilling fails in some cases. Here is one such case:

```
arthur@crypto:~/bbgo$  ./bbgo backtest --exchange binance -v --sync --sync-only --sync-from 2021-01-01 --config /tmp/3f80b776df8ec406f4064a608eec8319.yaml 2>&1
[0000]  INFO starting backtest with startTime Fri Jan  1 00:00:00 2021
[0000]  INFO starting synchronization...
[0000]  INFO synchronizing lastKLine for interval 4h from exchange binance
[0000]  INFO querying last kline exchange = binance AND symbol = 1INCHUSDT AND interval = 4h
[0000]  INFO found last checkpoint 2021-12-03 23:59:59.999 +0000 UTC
[0000]  INFO querying kline 1INCHUSDT 4h {0 2021-12-03 20:01:00 +0000 UTC <nil>} exchange=binance
[0000]  INFO synchronizing lastKLine for interval 12h from exchange binance
[0000]  INFO querying last kline exchange = binance AND symbol = 1INCHUSDT AND interval = 12h
[0000]  INFO found last checkpoint 2021-12-03 23:59:59.999 +0000 UTC
[0000]  INFO querying kline 1INCHUSDT 12h {0 2021-12-03 12:01:00 +0000 UTC <nil>} exchange=binance
[0000]  INFO synchronizing lastKLine for interval 3d from exchange binance
[0000]  INFO querying last kline exchange = binance AND symbol = 1INCHUSDT AND interval = 3d
[0001]  INFO found last checkpoint 2021-10-26 23:59:59.999 +0000 UTC
[0001]  INFO querying kline 1INCHUSDT 3d {0 2021-10-24 00:01:00 +0000 UTC <nil>} exchange=binance
Error: Error 1264: Out of range value for column 'taker_buy_base_volume' at row 1
[0001] FATAL cannot execute command error=Error 1264: Out of range value for column 'taker_buy_base_volume' at row 1
```

The content of the YAML config file:

```
arthur@crypto:~/bbgo$ cat /tmp/3f80b776df8ec406f4064a608eec8319.yaml
---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
backtest:
  startTime: "2021-01-01"
  endTime: "2021-01-15"
  symbols:
  - 1INCHUSDT
  account:
    balances:
      1INCH: 0.0
      USDT: 1000arthur@crypto:~/bbgo$ 

```

Any help extremely welcome.
