### ISSUE TITLE
Backtesting failing

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#291]
Very similar issue to the other (backfilling) one, but for backtesting instead of just backfilling this time.

```
arthur@crypto:~/bbgo$  ./bbgo backtest --exchange binance -v --sync --sync-only --sync-from 2021-01-01 --config /tmp/03f793aa26fcbe607146982e075f0fe3.yaml 
[0000]  INFO starting backtest with startTime Fri Jan  1 00:00:00 2021
[0000]  INFO starting synchronization...
[0000]  INFO synchronizing lastKLine for interval 12h from exchange binance
[0000]  INFO querying last kline exchange = binance AND symbol = DATAUSDT AND interval = 12h
[0005]  INFO querying kline DATAUSDT 12h {0 2021-01-01 00:00:00 +0000 UTC <nil>} exchange=binance
Error: Error 1264: Out of range value for column 'taker_buy_base_volume' at row 1
[0005] FATAL cannot execute command error=Error 1264: Out of range value for column 'taker_buy_base_volume' at row 1
```

The YAML file is:

```
arthur@crypto:~/bbgo$ cat /tmp/03f793aa26fcbe607146982e075f0fe3.yaml
---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
backtest:
  startTime: "2021-01-01"
  endTime: "2021-01-15"
  symbols:
  - DATAUSDT
  account:
    balances:
      DATA: 0.0
      USDT: 1000

arthur@crypto:~/bbgo$ 
```
