### ISSUE TITLE
fix backtest review

### ISSUE THREAD

**Issue by tony1223** [c9s/bbgo#355]
review/fix the backtest issue for ftx.

**Comment by tony1223** [comment]
1. backtest didn't support userconfig.sessions and envvarprefix related config for the source exchange (it used it for syncing the kline data)

2. give config
```
backtest:
  startTime: "2021-12-09"
  endTime: "2021-12-12"
  symbols:
    - MATICUSD
  account:
    balances:
      USDT: 3500.0
```

it shows the follwing error:
```
time="2021-12-12T18:03:13+08:00" level=info msg="starting synchronization..."
time="2021-12-12T18:03:23+08:00" level=info msg="querying last kline exchange = ftx AND symbol = MATICUSD AND interval = 1m"
time="2021-12-12T18:03:46+08:00" level=info msg="synchronizing lastKLine for interval 3d from exchange ftx"
time="2021-12-12T18:03:53+08:00" level=info msg="querying last kline exchange = ftx AND symbol = MATICUSD AND interval = 3d"
Error: interval 3d is not supported
time="2021-12-12T18:06:07+08:00" level=fatal msg="cannot execute command" error="interval 3d is not supported"
```
