### ISSUE TITLE
Profit spread should be bigger than 0

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#400]
I get the following error:

`Error: failed to validate the config: profit spread should bigger than 0`

Or in detail:

`{"error":"catch error in sim console log","attempts":1,"time":"Fri Dec 24 2021 23:04:48 GMT+0000 (Coordinated Universal Time)","fingerprint":"c03a555cbc0e7f5090a47234dc9392ff","result":"default result","stack":"Error: Command failed: cd /home/arthur/bbgo/ ;timeout -v --kill-after=120s 90s /home/arthur/bbgo/bbgo backtest --exchange binance --dotenv /home/arthur/tmp/bbgo-env/bbgo-env-DENTUSDT.yaml --config /home/arthur/tmp/bbgo-config/c03a555cbc0e7f5090a47234dc9392ff.yaml --base-asset-baseline --output /home/arthur/tmp/bbgo-cache/c03a555cbc0e7f5090a47234dc9392ff/ 2>&1\n    at checkExecSyncError (child_process.js:629:11)\n    at execSync (child_process.js:666:13)\n    at BBGO.attempt (/home/arthur/trade/lib/bbgo.js:159:22)\n    at BBGO.attempt (/home/arthur/trade/lib/bbgo.js:185:29)\n    at BBGO.attempt (/home/arthur/trade/lib/bbgo.js:185:29)\n    at BBGO.simulate (/home/arthur/trade/lib/bbgo.js:126:27)\n    at fitness (/home/arthur/trade/lib/basebot.js:66:27)\n    at BBGO.linearOptimize (/home/arthur/trade/lib/basebot.js:99:24)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)","message":"Command failed: cd /home/arthur/bbgo/ ;timeout -v --kill-after=120s 90s /home/arthur/bbgo/bbgo backtest --exchange binance --dotenv /home/arthur/tmp/bbgo-env/bbgo-env-DENTUSDT.yaml --config /home/arthur/tmp/bbgo-config/c03a555cbc0e7f5090a47234dc9392ff.yaml --base-asset-baseline --output /home/arthur/tmp/bbgo-cache/c03a555cbc0e7f5090a47234dc9392ff/ 2>&1","stdout":"Error: failed to validate the config: profit spread should bigger than 0\ntime=\"2021-12-24T23:04:48Z\" level=fatal msg=\"cannot execute command\" error=\"failed to validate the config: profit spread should bigger than 0\"\n","stderr":""}`

The config:

```
arthur@crypto:~$ cat /home/arthur/tmp/bbgo-config/c03a555cbc0e7f5090a47234dc9392ff.yaml
---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
backtest:
  startTime: "2020-01-10"
  endTime: "2020-01-11"
  symbols:
  - DENTUSDT
  account:
    makerCommission: 15 # TODO: Set the right values for binance, figure out what the number means
    takerCommission: 15
    balances:
      DENT: 0.0
      USDT: 10000
exchangeStrategies:
- on: binance
  grid:
    symbol: DENTUSDT
    # was: quantity: 125.00000000000000000000
    amount: 125.00000000000000000000
    gridNumber: 80.00000000000000000000
    profitSpread: 0.00000000170000000000
    upperPrice: 0.00015812000000000001
    lowerPrice: 0.00015798400000000001
    long: true
arthur@crypto:~$ 
```

I used to get this error only with xxx-BTC pairs (because BTC is so large), but now that I have added other coins, I even get it for xxx-USDT pairs.

Any help would be greatly appreciated.
