### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#401]
The error:

```
panic: runtime error: invalid memory address or nil pointer dereference\n
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41d2ed]\n\ngoroutine 1 [running]:\n
github.com/c9s/bbgo/pkg/backtest.(*SimplePriceMatching).PlaceOrder(_, {{0x0, 0x0}, {0xc000197f10, 0x7}, {0x11effac, 0x3}, {0x11f1da2, 0x5}, 0x41046f59ed6aea2f, ...})\n\t
/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/backtest/matching.go:162 +0x775\n
github.com/c9s/bbgo/pkg/backtest.Exchange.SubmitOrders({{0xc0001971d0, 0x7}, {0x13b1290, 0xc000780120}, 0xc000666c18, {0x0, 0xed7902f00, 0x0}, {0x0, 0xed7918080, ...}, ...}, ...)\n\t
/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13
```

The complete error:

```
{"error":"catch error in sim console log","attempts":3,"time":"Fri Dec 24 2021 23:08:02 GMT+0000 (Coordinated Universal Time)","fingerprint":"9744f81844deace19acb1a3b4607bc80","result":"default result","stack":"Error: Command failed: cd /home/arthur/bbgo/ ;timeout -v --kill-after=120s 90s /home/arthur/bbgo/bbgo backtest --exchange binance --dotenv /home/arthur/tmp/bbgo-env/bbgo-env-DGBUSDT.yaml --config /home/arthur/tmp/bbgo-config/9744f81844deace19acb1a3b4607bc80.yaml --base-asset-baseline --output /home/arthur/tmp/bbgo-cache/9744f81844deace19acb1a3b4607bc80/ 2>&1\n    at checkExecSyncError (child_process.js:629:11)\n    at execSync (child_process.js:666:13)\n    at BBGO.attempt (/home/arthur/trade/lib/bbgo.js:159:22)\n    at BBGO.simulate (/home/arthur/trade/lib/bbgo.js:126:27)\n    at fitness (/home/arthur/trade/lib/basebot.js:66:27)\n    at fmin.nelderMead (/home/arthur/trade/lib/basebot.js:114:19)\n    at Object.nelderMead (/home/arthur/trade/node_modules/fmin/build/fmin.js:154:28)\n    at BBGO.linearOptimize (/home/arthur/trade/lib/basebot.js:108:10)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)","message":"Command failed: cd /home/arthur/bbgo/ ;timeout -v --kill-after=120s 90s /home/arthur/bbgo/bbgo backtest --exchange binance --dotenv /home/arthur/tmp/bbgo-env/bbgo-env-DGBUSDT.yaml --config /home/arthur/tmp/bbgo-config/9744f81844deace19acb1a3b4607bc80.yaml --base-asset-baseline --output /home/arthur/tmp/bbgo-cache/9744f81844deace19acb1a3b4607bc80/ 2>&1","stdout":"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41d2ed]\n\ngoroutine 1 [running]:\ngithub.com/c9s/bbgo/pkg/backtest.(*SimplePriceMatching).PlaceOrder(_, {{0x0, 0x0}, {0xc000197f10, 0x7}, {0x11effac, 0x3}, {0x11f1da2, 0x5}, 0x41046f59ed6aea2f, ...})\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/backtest/matching.go:162 +0x775\ngithub.com/c9s/bbgo/pkg/backtest.Exchange.SubmitOrders({{0xc0001971d0, 0x7}, {0x13b1290, 0xc000780120}, 0xc000666c18, {0x0, 0xed7902f00, 0x0}, {0x0, 0xed7918080, ...}, ...}, ...)\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/backtest/exchange.go:176 +0x1b9\ngithub.com/c9s/bbgo/pkg/bbgo.(*ExchangeOrderExecutor).SubmitOrders(0xc000a72070, {0x1398210, 0xc000038088}, {0xc00089a000, 0xc00046c4b0, 0x7fb6cfcc85b8})\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/bbgo/order_execution.go:102 +0x112\ngithub.com/c9s/bbgo/pkg/strategy/grid.(*Strategy).placeGridBuyOrders(0xc00069cc60, {0x139e0b8, 0xc000a72070}, 0xc)\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/strategy/grid/strategy.go:345 +0x16b\ngithub.com/c9s/bbgo/pkg/strategy/grid.(*Strategy).placeGridOrders(0xc00069cc60, {0x139e0b8, 0xc000a72070}, 0x7fb6a91dbc00)\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/strategy/grid/strategy.go:371 +0x2ad\ngithub.com/c9s/bbgo/pkg/strategy/grid.(*Strategy).Run.func4()\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/strategy/grid/strategy.go:637 +0x32f\ngithub.com/c9s/bbgo/pkg/types.(*StandardStream).EmitStart(0xc00046c9b0)\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/types/standardstream_callbacks.go:13 +0x3a\ngithub.com/c9s/bbgo/pkg/backtest.(*Stream).Connect(0xc0001aa000, {0x7, 0x121bc5a})\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/backtest/stream.go:74 +0x5e5\ngithub.com/c9s/bbgo/pkg/bbgo.(*Environment).Connect(0xc00025e000, {0x13981d8, 0xc0001a3140})\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/bbgo/environment.go:456 +0x2e5\ngithub.com/c9s/bbgo/pkg/bbgo.(*Trader).Run(0xc000780060, {0x13981d8, 0xc0001a3140})\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/bbgo/trader.go:333 +0x32e\ngithub.com/c9s/bbgo/pkg/cmd.glob..func2(0x1b9e8c0, {0x11f110f, 0x9, 0x9})\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/cmd/backtest.go:299 +0x15eb\ngithub.com/spf13/cobra.(*Command).execute(0x1b9e8c0, {0xc000678b40, 0x9, 0x9})\n\t/home/arthur/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e\ngithub.com/spf13/cobra.(*Command).ExecuteC(0x1b9f5e0)\n\t/home/arthur/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/arthur/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\ngithub.com/c9s/bbgo/pkg/cmd.Execute()\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/pkg/cmd/root.go:173 +0x3e5\nmain.main()\n\t/home/arthur/go/pkg/mod/github.com/c9s/bbgo@v1.20.1-0.20211223162419-49e516b80e13/cmd/bbgo/main.go:8 +0x17\n","stderr":""}
```

The config:

```

arthur@crypto:~$ cat /home/arthur/tmp/bbgo-config/9744f81844deace19acb1a3b4607bc80.yaml
---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
backtest:
  startTime: "2021-01-13"
  endTime: "2021-01-14"
  symbols:
  - DGBUSDT
  account:
    makerCommission: 15 # TODO: Set the right values for binance, figure out what the number means
    takerCommission: 15
    balances:
      DGB: 0.0
      USDT: 10000
exchangeStrategies:
- on: binance
  grid:
    symbol: DGBUSDT
    # was: quantity: 3333.33333333333348491578
    amount: 3333.33333333333348491578
    gridNumber: 3.00000000000000000000
    profitSpread: 0.00503712000000000430
    upperPrice: 0.02754400000000000598
    lowerPrice: 0.01991199999999999914
    long: true
arthur@crypto:~$ 

```
