### ISSUE TITLE
Bug in grid Backtesting and report? 

### ISSUE THREAD

**Issue by ksidenko** [c9s/bbgo#631]
`(cd ../.. && ./build/bbgo/bbgo-darwin-amd64 backtest --base-asset-baseline --config grid-binance.yaml --debug --session binance  --output output --subdir);`

grid.yaml
```
exchangeStrategies:
- on: binance
  grid:
    symbol: BTCUSDT
    quantity: 0.0005
    gridNumber: 3
    profitSpread: 1000.0
    upperPrice: 30000
    lowerPrice: 27000
    long: false
```

<img width="963" alt="image" src="https://user-images.githubusercontent.com/8588439/169658238-7a3cbf3d-7bb3-46ab-b92a-004efcc94167.png">

<img width="1792" alt="Screenshot 2022-05-21 at 22 25 56" src="https://user-images.githubusercontent.com/8588439/169658495-0cd5d053-ca65-4f14-8a23-3a1fd28a7eb4.png">

Issues: 
* 1 order — ok
* 2-3 orders — strange time, not sync with graph in report, buy / sell order reversed graph 
* at 02:00 - no order in report at all
