### ISSUE TITLE
Bot is leaving dust behind

### ISSUE THREAD

**Issue by milewski** [c9s/bbgo#858]
Hi I think there is an issue with the fee calculation, currently Binance fee is 0 but it keeps buying at: `0.01` selling at `0.009` 

I have the following:

```yaml
sessions:
  binance:
    name: binance
    exchange: binance
    envVarPrefix: BINANCE
    takerFeeRate: 0.0
    makerFeeRate: 0.0
    orderExecutor: {}
```

------

And backtesting also does not take the takerFee/MakerFee: 0 in consideration
