### ISSUE TITLE
請問該怎麼讓 bollgrid 策略一直跑下去呢？

### ISSUE THREAD

**Issue by Larry850806** [c9s/bbgo#93]
c9s 大大你好，我這兩天有嘗試使用 bbgo 的 bollgrid 策略，但遇到一些問題

我的 binary 是 BBGO v1.10.0 Linux 版本，以下是我的設定檔

```yaml
---
riskControls:
  sessionBased:
    max:
      orderExecutor:
        bySymbol:
          BTCUSDT:
            # basic risk control order executor
            basic:
              minQuoteBalance: 0.0
              maxBaseAssetBalance: 0.0 # disable
              minBaseAssetBalance: 0.0 # disable
              maxOrderAmount: 3000.0

exchangeStrategies:
  - on: max
    bollgrid:
      symbol: BTCUSDT
      interval: 5m
      gridNumber: 20
      quantity: 0.0015
      profitSpread: 50.0
```

一開始執行時會 log 出很多 submit order 的訊息，看起來都很正常，而且到 MAX 交易所上看確實也有正常掛單

<img width="1440" alt="Screen Shot 2021-01-29 at 3 04 28 PM" src="https://user-images.githubusercontent.com/10403741/106242837-4aab4000-6243-11eb-9067-e5c973bd249e.png">

但執行了一陣子，全部的單都成交了（買進 BTC 又賣出）之後，BBGO 就不會繼續下單了，只有每分鐘把最新的 kline 價錢 log 出來。所以我又會把程式關掉重新執行，他才會再開始下一波的下單交易

<img width="1440" alt="Screen Shot 2021-01-29 at 3 05 49 PM" src="https://user-images.githubusercontent.com/10403741/106242981-83e3b000-6243-11eb-8d31-e4de20d139fe.png">

我希望他可以在一波單結束之後就繼續下一波，不用自己重開程式，所以想請問是我的設定檔哪部分寫錯了嗎，還是說本來執行一次就是只有進行一波買進、賣出？

謝謝 c9s，能寫出 bbgo 真的很厲害
